### ISSUE TITLE
docker container:  invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by softlion** [streamr-dev/network#1976]
After a couple of minutes, the streamr docker container logs start containing undisplayable chars:

```
> docker logs -f  streamr1

INFO [2023-09-25T20:12:43.707] (WebRtcEndpoint      ): Connected to 16 peers
INFO [2023-09-25T20:17:43.707] (WebRtcEndpoint      ): Connected to 16 peers
INFO [2023-09-25T20:22:43.707] (WebRtcEndpoint      ): Connected to 16 peers
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```

The only workaround is to use -n `docker logs -f -n 10 streamr1`

Also, my streamr node is now KO, it used to be OK so I let it run for a few weeks. I come back and it's KO. Why ?

**Comment by hpihkala** [comment]
Hi, apologies for the slow response. We've been heads down working on the upcoming Streamr 1.0 network.

If I understand correctly, your report includes two separate things:
- Weird characters logged
- Node crashed

As there's a major milestone update coming, it would be great to understand whether the issues are already fixed in that.

Have you tried [running a node in the Streamr 1.0 pre-testnet](https://docs.streamr.network/guides/become-an-operator), and have you noticed similar problems there?

In general, it's a good idea to have some process manager in place to restart the node in case it exits for any reason.

**Comment by softlion** [comment]
no more issue with pre testnet version.

**Comment by softlion** [comment]
note that the issue happens because docker was not installed with the official package.
