### ISSUE TITLE
addToStorageNode does not get the address.

### ISSUE THREAD

**Issue by oharkins** [streamr-dev/network#332]
The only way to make this work is to put the storage node id 0xRedacted in, not one of these. 

await stream.addToStorageNode(STREAMR_STORAGE_NODE_GERMANY)

`await stream.addToStorageNode(StorageNode.STREAMR_GERMANY)`

**Comment by fonty1** [comment]
The docs could be clearer on this point, thanks for bringing it into my attention @oharkins - I went through this on the `5.5.7` `streamr-client` and collected some tips that I'll add to the docs.

1. Import `StorageNode` like so, otherwise it will be `undefined` as you have mentioned:
`const { StorageNode, StreamrClient } = require('streamr-client').StreamrClient` 
2. Always `await` or promise-then stream creation (async operation, soon to be onchain and even slower :))
3. Always create a stream using `id` rather than `name`. E.g. 
```
const { StorageNode, StreamrClient } = require('streamr-client').StreamrClient

var client = new StreamrClient({
  auth: {
    privateKey: '...',
  },
})

async function start() {

  const stream = await client.getOrCreateStream({
        id: '0x56E968C21990a20899e52FF7a3422cDA3b492481/encryption-example/boot/fox/sta'
  })
  console.log(stream)
  await stream.addToStorageNode(StorageNode.STREAMR_GERMANY)
}
start()
```
